### ISSUE TITLE
Composite chain node

### ISSUE THREAD

**Issue by mathias-luedtke** [ros-industrial/ros_canopen#187]
Instead of virtual inheritance profile-specific layers could be added via plugin-based profile handlers.
The would allow mixed sensor/actor chains in one ROS node.

So each node entry in config could contain a list of profile specific chains:

``` YAML
nodes:
  - name: node1
    id: 1
    eds_pkg: my_config_package # optionals package  name for relative path
    eds_file: "my_config.eds" # path to EDS/DCF file
    chains: [canopen_motor_node::RosControl402Chain]
```
