### ISSUE TITLE
Support ros_control mixed-mode controllers

### ISSUE THREAD

**Issue by mathias-luedtke** [ros-industrial/ros_canopen#197]
The current config layout does require a single drive mode (`required_drive_mode`).
In order to support mixed-mode controllers the param should read a dictionary entry `required_drive_modes` as well.

```yaml
required_drive_mode: 2
required_drive_modes:
  special_joint: 3
```
