### ISSUE TITLE
Could not find resource 'left_wheel' in 'hardware_interface::VelocityJointInterface'.

### ISSUE THREAD

**Issue by Timple** [ros-industrial/ros_canopen#257]
We get an error trying to operate our CANOpen motors. The velocity interface does not seem to be registered.

```bash
[ERROR]: Exception thrown while initializing controller base_controller.
Could not find resource 'left_wheel' in 'hardware_interface::VelocityJointInterface'.
[ERROR]: Initializing controller 'base_controller' failed
```

In simulation (gazebo) and on other hardware (etherCAT) we have the same robot running including the same urdf and the same ros_control.yaml file. So the parameters should be correct.

I have the feeling that canopen_motor_node does not 'know' that our motor supports velocity setpoints. Is there something we're doing wrong?

Relevant pieces of config:

**ros_control.yaml**
```yaml
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

base_controller:
  type        : "diff_drive_controller/DiffDriveController"
  open_loop   : true
  left_wheel  : 'left_wheel'
  right_wheel : 'right_wheel'

left_wheel_controller:
  type: velocity_controllers/JointVelocityController
  joint: left_wheel
  required_drive_mode: 3
```

**canopen.yaml**
```yaml
canopen_motor_chain_node:
  bus:
    device: can0
  sync:
    interval_ms: 100
    overflow: 0
  nodes:
    node2:
      id: 2
      name: left_wheel
      eds_pkg: "ourbot_control"
      eds_file: "config/HBI3760-4/Engel_Drive_1_9.eds"
    node3:
      id: 3
      name: right_wheel
      eds_pkg: "ourbot_control"
      eds_file: "config/HBI3760-4/Engel_Drive_1_9.eds"

hardware_interface:
  joints:
    - left_wheel
    - right_wheel

joint_group_velocity_controller:
  joints:
    - left_wheel
    - right_wheel
  required_drive_mode: 3
  type: velocity_controllers/JointGroupVelocityController
```

**ourbot.urdf**
```xml
 <transmission name="left_wheel_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_wheel">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_wheel_actuator">
        <mechanicalReduction>7</mechanicalReduction>
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </actuator>
</transmission>

<transmission name="right_wheel_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_wheel">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_wheel_actuator">
        <mechanicalReduction>7</mechanicalReduction>
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </actuator>
</transmission>
</robot>
```
