### ISSUE TITLE
joint_state_publisher publishes at 2hz while set at 10hz

### ISSUE THREAD

**Issue by Timple** [ros-industrial/ros_canopen#259]
`joint_state_publisher` and the `diff_drive_controller` both run at 2hz while set to 10hz.

The `joint_state_publisher` starts at about 3-4hz but reduces to 2hz when the `diff_drive_controller` is also enabled.

This is also the frequency at which the canmotors are operated (I can hear the velocity changes at around 2hz)

Relevant configs:
```yaml
canopen_motor_chain_node:
  bus:
    device: can0

  sync:
    interval_ms: 100
    overflow: 0

  defaults:
    eds_file: "config/HBI3760-4/Engel_Drive_1_9_ROS_compatible.eds"
    dcf_overlay:
      "1800sub2": "1" # Only send PDO on sync message (Reduces chatter on CANbus)
      "1801sub2": "1"
      "1017": "1000" # heartbeat producer [ms]

  nodes:
    node2:
      id: 2
      name: left_wheel
      dcf_overlay:
        "607E": "1" # Reverse Polarity

    node3:
      id: 3
      name: right_wheel

  diagnostic_period: 1.0

hardware_interface:
  joints:
    - left_wheel
    - right_wheel
```

```yaml
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 10

base_controller:
  type        : "diff_drive_controller/DiffDriveController"
  open_loop   : false
  left_wheel  : 'left_wheel'
  right_wheel : 'right_wheel'
  publish_rate: 10.0               # default: 50
  publish_cmd : true

  wheel_radius        : 0.1
  wheel_separation    : 0.5
  base_frame_id       : 'base_link'
  enable_odom_tf      : false
  required_drive_mode : 3

left_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: left_wheel
  required_drive_mode: 3

right_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: right_wheel
  required_drive_mode: 3

```

* Changing bitrate of the can had no influence
* Changing the sync interval helped a little bit, could reach 4.7hz
* Setting PDO to asynchonous with a inhibit time of 20hz did not help
* The computer does not seem busy (htop <5%) (canbusload <2%)
* using branch kinetic-devel

_it seems an issue, if a answers.ros.org is better suited let me know_
