### ISSUE TITLE
Add support for virtual joints in canopen_motor_node

### ISSUE THREAD

**Issue by akosodry** [ros-industrial/ros_canopen#298]
Lets say, there is a `JointTrajectoryController` defined with five joints: `joint_1`, `joint_2`, .. `joint_5`, i.e.:

```
robot_5s_arm_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
```

**However**: only 3 joints are possible to be tested on the real harware, lets say, `joint_1`, `joint_2` and `joint_3`. Therefore the driver `yaml` file, that is passed to the `canopen_motor_node` contains only the nodes of joint_1-joint_3, i.e.:

```
nodes:
  - name: joint_1
    id: 1
  - name: joint_2
    id: 2
  - name: joint_3
    id: 3
```

Is it possible to **virtually** link `joint_4` and `joint_5` to `canopen_motor_node`? Since, currently the node crashes with the error saying that there is no `hardware interface` for `joint_4` and `joint_5`.

Thank you in advance.
