### ISSUE TITLE
Executable Sample / Yaml-File-Support / Heartbeat missing

### ISSUE THREAD

**Issue by rostest** [ros-industrial/ros_canopen#316]
Hi,

for a specific project I want to extend ROS with drivers for a number of CANopen devices. A netdevice can0 is installed under ROS and candump from the can-utils receives data over the CANbus as soon as a master sends its heartbeats.

Now I want to build my own ROS node based on canopen_chain_node from the package ros_canopen (https://github.com/ros-industrial/ros_canopen.git), which communicates with the CANopen slaves. Do you know a completely executable example? As CAN slave I first use a cangineberry with Raspberry Pi.

If I start canopen_chain_node from ros_canopen-distribution 
via
``
roslaunch -v --screen canopen_chain_node chain.launch yaml:=test.yaml
``
the ros-node runs, but the command 
``
candump -ta can0"
``
shows no activity on the CNA-bus.

The yaml file looks like this:

```
bus:
  device: can0
  driver_plugin: can::SocketCANInterface
  master_allocator: canopen::SimpleMaster::Allocator
sync:
  interval_ms: 10
  overflow: 0
heartbeat:
  rate: 100 # simple heartbeat producer, optional!
  msg: "77f#05" # message to send, cansend format: heartbeat of node 127 with status 5=Started
nodes:
  node1:
    id: 0x08
    eds_file: /home/test/catkin_ws/test/eds/CiA402_Stepper_Node8.eds
    publish: ["1018sub1!"] # object index 1018sub1 (vendor id) should always exist
```

I would have expected at least some heartbeat messages with candump. Do you have an idea - maybe a basic configuration is still missing?

If you know articles about the structure of the yaml file for canopen_chain_node or example projects, I would be very happy about hints. Maybe there is already a ros_canopen project that communicates with a CAN-device simulated by cangineberry?

Many thanks and best regards
