### ISSUE TITLE
Can I use this package for the device without "Consumer Heartbeat Time" support?

### ISSUE THREAD

**Issue by bxc237** [ros-industrial/ros_canopen#367]
Hi, I saw these lines in every example:

```
heartbeat: # simple heartbeat producer
  rate: 20 # heartbeat rate
  msg: "77f#05" # message to send, cansend format: heartbeat of node 127 with status 5=Started
defaults:
  dcf_overlay: # "ObjectID": "ParameterValue" (both as strings)
    "1016sub1" : "0x7F0064" # heartbeat timeout of 100 ms for master at 127
    "1017": "100" # heartbeat producer
```
My device supports both heartbeat and node guarding (ros_canopen does not support). However, according to the eds file, the device does not have the [1016] Consumer Heartbeat Time entry. Then can I still use this package for canopen control? THX!
