### ISSUE TITLE
CanOpen refuses to initialize canopen_chain_node (Initializing failed: could not reset node '8')

### ISSUE THREAD

**Issue by mal-a-chillingg** [ros-industrial/ros_canopen#381]
To whoever is willing to help with an answer, here is the issue I am having. I am setting up a RobotTeq HBL2360A drive and I have the EDS file and everything. I have put together what I believe is a correct config and launch file. For now I am running the system as a canopen_chain_node and I have manually tested the drives communication with candump and cansend and there are no issues as far as I can tell. The drive responds correctly to sync commands and NMT commands when I manually send them. When I launch the setup I get the following in ROSCore.

```
CLEAR PARAMETERS
 * /canopen_chain_node/

PARAMETERS
 * /canopen_chain_node/bus/device: can0
 * /canopen_chain_node/nodes/node1/eds_file: /config/HBL2360A.eds
 * /canopen_chain_node/nodes/node1/eds_pkg: little_pig_ctrl
 * /canopen_chain_node/nodes/node1/id: 8
 * /canopen_chain_node/sync/interval_ms: 2000
 * /canopen_chain_node/sync/overflow: 0
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /
    canopen_chain_node (canopen_chain_node/canopen_chain_node)

auto-starting new master
process[master]: started with pid [28932]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 0bbb7a12-55c5-11ea-bd2f-00044bddba3d
process[rosout-1]: started with pid [28943]
started core service [/rosout]
process[canopen_chain_node-2]: started with pid [28951]
```

As far as I can tell there is nothing wrong at this point but when I go to initialize the driver it will not work. I get the following message in the terminal

```
success: False
message: "could not reset node '8'"
```

Meanwhile in ROSCORE the following messages are generated.

```
[ INFO] [1582411558.289981301]: Initializing...
[ INFO] [1582411558.293634531]: Current state: 1 device error: system:0 internal_error: 0 (OK)
[ INFO] [1582411558.296560564]: Current state: 2 device error: system:0 internal_error: 0 (OK)
[ERROR] [1582411569.308112997]: Did not receive a response message
[ WARN] [1582411569.311083926]: discarded message 
[ INFO] [1582411569.314714468]: Current state: 2 device error: system:125 internal_error: 0 (OK)
[ INFO] [1582411569.315000003]: Current state: 0 device error: system:125 internal_error: 0 (OK)
[ INFO] [1582411569.315333857]: Current state: 0 device error: system:0 internal_error: 0 (OK)
[ INFO] [1582411569.315685440]: Current state: 0 device error: system:0 internal_error: 0 (OK)
[ERROR] [1582411569.317187704]: Initializing failed: could not reset node '8'
```

No matter what I do I cannot get the node to initialize. I am also monitoring the candump on can1 at the same time and here are the results I am getting

```
ursa@ursa-major:~/catkin_ws/src/little_pig_ctrl/config$ candump can1
can1  000   [2]  82 08
can1  708   [1]  7F
can1  708   [1]  7F
can1  708   [1]  7F
can1  708   [1]  7F
can1  708   [1]  7F
can1  708   [1]  7F
can1  708   [1]  7F
can1  708   [1]  7F
can1  708   [1]  7F
can1  708   [1]  7F
can1  708   [1]  7F
can1  608   [8]  2B 17 10 00 00 00 00 00
can1  588   [8]  60 17 10 00 00 00 00 00
can1  608   [8]  80 17 10 00 00 00 04 05
can1  000   [2]  02 08
```

All of the documentation I have read sounds like this is exactly what I would expect from the drive. After receiving the NMT command to reset it goes to pre-operational state and just waits. However, Canopen does nothing more and then eventually gives up and tells the node to shut up. Is there anything wrong in what I am seeing in the date. I have already checked the baud rates and I can't find any issues there, I am set at 500k on both devices. I also have tested this with and without 402 enabled on the drive to no avail. I plan to eventually migrate to 402; however, I don't understand enough about it yet and from my understanding I should have full operation on canopen_chain_node.

Here is my Launch file

```xml
<launch>
  <node name="canopen_chain_node" pkg="canopen_chain_node" type="canopen_chain_node" output="screen" clear_params="true" >
<rosparam command="load" file="$(find little_pig_ctrl)/config/can_old_config.yaml" />
</node>
</launch>
```

Here is my config file

```yaml
bus:
  device: can0 # socketcan network
  #loopback: false # socket should loop back messages
  #driver_plugin: can::SocketCANInterface
  #master_allocator: canopen::SimpleMaster::Allocator
sync:
  interval_ms: 2000 #100 # set to 0 to disable sync
  #update_ms: <interval_ms> #update interval of control loop, must be set explecitly if sync is disabled
  overflow: 0 # overflow sync counter at value or do not set it (0, default)
  #heartbeat: # simple heartbeat producer, optional!
  #rate: 2000 # heartbeat rate
  #msg: "701#05" # message to send, cansend format: heartbeat of node 1 with status 5=Started

nodes:
  node1:
    id: 8
    eds_pkg: little_pig_ctrl
    eds_file: "/config/HBL2360A.eds"
```

I appreciate any help you guys can provide. I have been beating this problem around for the last day and I am at my wits end. Thanks
